---
title: "Aula 1"
author: "João Miguel Maraschin Santos, 2024"
date: "2024-03-13"
output: html_document
editor_options: 
  chunk_output_type: console
---

#1. Operadores
```{r}
1+1 #adição
2*2 #multiplicação
4/2 #divisão
5^2 #potenciação
5**2 #potenciação
sqrt(100) #radiciação
log(pi) #logaritmo
log10(pi) #logaritmo
seq(1,10) #sequência
(1:10)

a<-10
b<-2
x<-1:10

y=a*x+b
plot(y)
lines(y)

z=x^2+b
plot(z)
lines(z)
```


#2. Funções
```{r}
#Bhhaskara -> 4x^2-3*x-1=0
a<-4
b<--3
c<--1

d<-((b^2)-4*a*c)

x1<-(-b+sqrt(d))/(2*a)
x2<-(-b-sqrt(d))/(2*a)

bk<-function(a,b,c){                                                            #em função de a,b,c
  d<-((b^2)-4*a*c)                                                              #definir o delta 
  if (d < 0) {                                                                  #condição matemática básica
    return("A equação não possui raízes reais.")                                #resposta para a condição
  } 
  else {
  x1<-(-b+sqrt(d))/(2*a)                                                        #x1 = +
  x2<-(-b-sqrt(d))/(2*a)                                                        #x2 = -
  return(c(x1,x2))                                                              #resposta
}}


#5x^2-2x+7=0
bk(,,)


#4x^2-3*x-1=0
bk(,,)

rt<-bk(,,)                                                                      #definir as raízes

y_intercept <- c
x_intercecpt <- rt


#Gráfico
curve(a*x^2 + b*x + c,                                                          #definir a função da curva
      from = -5, to = 5,                                                        #limites
      ylim = c(-5, 5),
      add=FALSE)
points(rt,                                                                      #valores dos pontos
       a*rt^2 + b*rt + c,                                                       #função ds pontos
       col = "green", pch = 16)
text(0, y_intercept,                                                            #x,y
     paste("", y_intercept),                                                    #texto e valor
     pos = 4, col = "red")
text(1.5,0,
     paste(""),
     pos = (3), col = "blue")
text(,,
     paste(""),
     pos = (3),col="blue")
abline(h=0)
abline(v=0)
```


#3 Tipos de variáveis
```{r}
#Tipos de variáveis
#Numeric
a=0.1
is.numeric(a)
is.integer(a)
as.integer(a)


#interger
b=12L
is.numeric(b)
is.integer(b)


#character ou string
c="geologia"


#logic
d=TRUE
  2+2==4

e=FALSE
  2+2==5
  
class(a)
class(b)
class(c)
class(d)
class(e)
```


#4 Tipos de estruturas
```{r}
#matrix -> tabela com variáveis em duas dimensões
matrix<-matrix(1:10, nrow = 5, ncol =2, byrow=FALSE)
matrix

matrix[3,1] #posição
matrix[1,] #linha
matrix[,1] #coluna


#vector -> sequência de valores
par<-seq(2,20,2)
imp<-seq(1,19,2)

cbind(imp,par) #juntar os vetores em uma matriz
rbind(imp,par) #juntar os vetores em uma matriz


#data frame -> "matrix" ue aceita difetentes tipos de variáveis 
A <- c("arenito", "conglomerado", "pelito")
B <- c(2.00, 2.001, 0.063)
C <- c("média", "ruim", "boa")

dados <- data.frame(litologias=A,grainsize=B,selecao=C)
print(dados)


#factor -> utilização para variáveis categóricas
litologia <- factor(c("pelito","arenito","pelito","arenito","pelito","conglomerado","conglomerado")) #criar um factor
  print(litologia)
  levels(litologia)
  print(litologia[2])
  print(litologia[3])

lito_abc <-factor(c("pelito","arenito","pelito","arenito","pelito","conglomerado","conglomerado")) #criando e reorganizando um factor
  lito_abc[1] <- "arenito"
  lito_abc[2] <- "conglomerado"
  lito_abc[3] <- "pelito"
  print(lito_abc)
  print(lito_abc[1])
  
size <- c(pelito = 0.063, arenito = 2, conglomerado = 2.1) #vetor tamanho de grão

  grainsize <- size[match(as.character(lito_abc), names(size))] #organizando o vetor "size" com o vector "litologia"
  dados_lito <- data.frame(Litologia = lito_abc, Tamanho_grao = grainsize) #criando o data frame

print(dados_lito)


#list -> bloco de informações tridimensional (x,y,z) com diferentes tipos de dados
x<-1:4
y<-10:13
z<-2:7
lista<-list(x,y,z)
print(lista)

lista[[2]] #selecionar a lista com dois [[]]
lista[[2]][3] #selecionar a lista com dois [[]] e a posição com um []


#array ->  estrutura multidimensional com mesmo tipos de dados
testemunho <- array(data = c(10,15,10,10,10,15,20,10,15,20,5,5,10,15,20,10), #valores
              dim = c(4,3,2),                                          # quantificação das dimensões
              dimnames = list(poco = c("1","2","3","4"),                    #definição das dimensões
                              lito = c("arenito","conglomerado","pelito"),
                              campo = c("A","B")))
print(testemunho)
```


